spring:
  application:
    name: xiaojiguanli
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/performance-manage?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  typeAliasesPackage: com.abc.performancemanagement.pojo
  configuration:
    map-underscore-to-camel-case: true